name: xelis_dart_sdk
description: Software Development Kit in Dart to build Apps for the Xelis Blockchain.
version: 0.0.2
repository: https://github.com/xelis-project/xelis-dart-jdk

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.23.1