name: xelis_dart_sdk
description: Software Development Kit in Dart to build Apps for the XELIS Blockchain.
version: 0.23.2
repository: https://github.com/xelis-project/xelis-dart-jdk

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  convert: ^3.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.3
  jsontool: ^2.1.0
  logging: ^1.3.0
  very_good_analysis: ^7.0.0
  web_socket_client: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^5.1.1
  test: ^1.25.14
