name: xelis_dart_sdk
description: Software Development Kit in Dart to build Apps for the Xelis Blockchain.
version: 0.20.0
repository: https://github.com/xelis-project/xelis-dart-jdk

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_rpc_2: ^3.0.2
  jsontool: ^2.1.0
  logging: ^1.2.0
  very_good_analysis: ^6.0.0
  web_socket_client: ^0.1.4

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
