name: xelis_dart_sdk
description: Software Development Kit in Dart to build Apps for the Xelis Blockchain.
version: 0.14.0
repository: https://github.com/xelis-project/xelis-dart-jdk

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_rpc_2: ^3.0.2
  jsontool: ^1.2.0
  logging: ^1.2.0
  very_good_analysis: ^5.1.0
  web_socket_client: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.1
